import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const GITHUB_API = "https://api.github.com";

function loadEnv() {
  try {
    const envFile = readFileSync(".env", "utf8");
    for (const line of envFile.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      if (val && !process.env[key]) process.env[key] = val;
    }
  } catch {}
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// ── GitHub API ──────────────────────────────────────────────

async function gh(path, token, opts = {}) {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...opts,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...opts.headers,
    },
    body: opts.body ? JSON.stringify(opts.body) : undefined,
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`GitHub ${res.status}: ${text.slice(0, 300)}`);
  }
  return res.json();
}

async function findExistingIssue(owner, repo, title, token) {
  const q = encodeURIComponent(`repo:${owner}/${repo} in:title "${title}" type:issue`);
  const data = await gh(`/search/issues?q=${q}`, token);
  return data.items?.find((i) => i.title === title) || null;
}

async function createIssue(owner, repo, title, body, labels, token) {
  return gh(`/repos/${owner}/${repo}/issues`, token, {
    method: "POST",
    body: { title, body, labels },
  });
}

async function updateIssue(owner, repo, issueNum, body, token) {
  return gh(`/repos/${owner}/${repo}/issues/${issueNum}`, token, {
    method: "PATCH",
    body: { body },
  });
}

async function createOrUpdate(owner, repo, title, body, labels, token) {
  const existing = await findExistingIssue(owner, repo, title, token);
  if (existing) {
    await updateIssue(owner, repo, existing.number, body, token);
    return { url: existing.html_url, updated: true };
  }
  const issue = await createIssue(owner, repo, title, body, labels, token);
  return { url: issue.html_url, updated: false };
}

// ── Issue formatters ────────────────────────────────────────

function formatFindings(findings) {
  const byFile = {};
  for (const f of findings) {
    const file = f.component?.split(":").slice(1).join(":") || "unknown";
    if (!byFile[file]) byFile[file] = [];
    byFile[file].push(f);
  }

  const lines = [];
  for (const [file, items] of Object.entries(byFile)) {
    lines.push(`### \`${file}\``);
    for (const f of items) {
      const loc = f.textRange
        ? `L${f.textRange.startLine}${f.textRange.startLine !== f.textRange.endLine ? "-" + f.textRange.endLine : ""}`
        : "";
      const sev = f.severity || "INFO";
      const tags = f.tags?.length ? ` \`${f.tags.join("`, `")}\`` : "";
      lines.push(`- [ ] **${sev}** ${loc} — ${f.message}${tags}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function makeBugIssue(report) {
  const n = report.issues.bugs.length;
  return [
    `## ${n} Bug${n !== 1 ? "s" : ""} Found`,
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Bugs | ${n} |`,
    `| Reliability Rating | ${report.metrics.reliabilityRating}/5 |`,
    `| Quality Gate | ${report.qualityGatePassed ? "PASS" : "FAIL"} |`,
    "",
    "---",
    "",
    formatFindings(report.issues.bugs),
    "",
    "---",
    "_Report generated by [GitRoll](https://gitroll.io) scan._",
  ].join("\n");
}

function makeCodeSmellIssue(report) {
  const n = report.issues.codeSmells.length;
  return [
    `## ${n} Code Smell${n !== 1 ? "s" : ""} Found`,
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Code Smells | ${n} |`,
    `| Maintainability Rating | ${report.metrics.sqaleRating}/5 |`,
    `| Lines of Code | ${report.metrics.ncloc.toLocaleString()} |`,
    "",
    "---",
    "",
    formatFindings(report.issues.codeSmells),
    "",
    "---",
    "_Report generated by [GitRoll](https://gitroll.io) scan._",
  ].join("\n");
}

function makeVulnIssue(report) {
  const n = report.issues.vulnerabilities.length;
  return [
    `## ${n} Vulnerabilit${n !== 1 ? "ies" : "y"} Found`,
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Vulnerabilities | ${n} |`,
    `| Security Rating | ${report.metrics.securityRating}/5 |`,
    `| Quality Gate | ${report.qualityGatePassed ? "PASS" : "FAIL"} |`,
    "",
    "---",
    "",
    formatFindings(report.issues.vulnerabilities),
    "",
    "---",
    "_Report generated by [GitRoll](https://gitroll.io) scan._",
  ].join("\n");
}

function makeSummaryIssue(report) {
  const m = report.metrics;
  const sections = [];

  if (m.bugs > 0) {
    sections.push(
      `### Bugs: ${m.bugs}`,
      `- Reliability Rating: ${m.reliabilityRating}/5`,
      ""
    );
  }
  if (m.codeSmells > 0) {
    sections.push(
      `### Code Smells: ${m.codeSmells}`,
      `- Maintainability Rating: ${m.sqaleRating}/5`,
      ""
    );
  }
  if (m.vulnerabilities > 0) {
    sections.push(
      `### Vulnerabilities: ${m.vulnerabilities}`,
      `- Security Rating: ${m.securityRating}/5`,
      ""
    );
  }

  if (sections.length === 0) return null;

  return [
    `## GitRoll Scan Results`,
    "",
    `Detailed issue breakdowns are not available for this scan (older scan data).`,
    `The following issues were detected at a summary level:`,
    "",
    ...sections,
    `**Quality Gate:** ${report.qualityGatePassed ? "PASS" : "FAIL"}`,
    `**Lines of Code:** ${report.metrics.ncloc.toLocaleString()}`,
    "",
    "---",
    "_Report generated by [GitRoll](https://gitroll.io) scan. Re-scan the repo on GitRoll for detailed findings._",
  ].join("\n");
}

// ── Main ────────────────────────────────────────────────────

async function main() {
  loadEnv();

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.error("Error: GITHUB_TOKEN not set in .env or environment.");
    process.exit(1);
  }

  const reportsDir = join(process.cwd(), "reports");
  const files = readdirSync(reportsDir).filter(
    (f) => f.endsWith(".json") && f !== "_index.json"
  );

  if (files.length === 0) {
    console.error("No report files found in reports/. Run export-reports.mjs first.");
    process.exit(1);
  }

  // Allow filtering to specific repos via args
  const args = process.argv.slice(2);

  console.log(`Processing ${files.length} reports...\n`);

  for (const file of files) {
    const report = JSON.parse(readFileSync(join(reportsDir, file), "utf8"));
    const [owner, repo] = report.repo.split("/");

    // Filter if args provided
    if (args.length > 0 && !args.some((a) => report.repo.includes(a))) continue;

    const hasDetails = report.detailStatus === "available";
    const bugCount = report.totals.bugs;
    const smellCount = report.totals.codeSmells;
    const vulnCount = report.totals.vulnerabilities;

    if (bugCount + smellCount + vulnCount === 0) {
      console.log(`  ${report.repo} — clean, skipping`);
      continue;
    }

    console.log(`  ${report.repo} (${bugCount}B ${smellCount}S ${vulnCount}V)`);

    if (!hasDetails) {
      // Summary-only: one combined issue
      const body = makeSummaryIssue(report);
      if (!body) continue;
      const title = `[GitRoll] Scan Results: ${bugCount} bugs, ${smellCount} code smells, ${vulnCount} vulnerabilities`;

      try {
        const result = await createOrUpdate(
          owner, repo, title, body,
          ["gitroll", "code-quality"],
          token
        );
        console.log(`    ${result.updated ? "updated" : "created"}: ${result.url}`);
      } catch (e) {
        console.error(`    FAILED: ${e.message}`);
      }

      await sleep(1500);
      continue;
    }

    // Detailed: one issue per category
    const tasks = [];

    if (bugCount > 0) {
      tasks.push({
        title: `[GitRoll] ${bugCount} Bug${bugCount !== 1 ? "s" : ""} Found`,
        body: makeBugIssue(report),
        labels: ["gitroll", "bug"],
      });
    }

    if (smellCount > 0) {
      tasks.push({
        title: `[GitRoll] ${smellCount} Code Smell${smellCount !== 1 ? "s" : ""} Found`,
        body: makeCodeSmellIssue(report),
        labels: ["gitroll", "code-smell"],
      });
    }

    if (vulnCount > 0) {
      tasks.push({
        title: `[GitRoll] ${vulnCount} Vulnerabilit${vulnCount !== 1 ? "ies" : "y"} Found`,
        body: makeVulnIssue(report),
        labels: ["gitroll", "security"],
      });
    }

    for (const task of tasks) {
      try {
        const result = await createOrUpdate(
          owner, repo, task.title, task.body,
          task.labels,
          token
        );
        console.log(`    ${result.updated ? "updated" : "created"}: ${result.url}`);
      } catch (e) {
        console.error(`    FAILED: ${e.message}`);
      }
      await sleep(1500);
    }
  }

  console.log("\nDone.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
