import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";

function formatFindings(findings: Record<string, unknown>[]) {
  const byFile: Record<string, Record<string, unknown>[]> = {};
  for (const f of findings) {
    const comp = f.component as string;
    const file = comp?.split(":").slice(1).join(":") || "unknown";
    if (!byFile[file]) byFile[file] = [];
    byFile[file].push(f);
  }
  const lines: string[] = [];
  for (const [file, items] of Object.entries(byFile)) {
    lines.push(`### \`${file}\``);
    for (const f of items) {
      const tr = f.textRange as Record<string, number> | undefined;
      const loc = tr ? `L${tr.startLine}${tr.startLine !== tr.endLine ? "-" + tr.endLine : ""}` : "";
      const sev = (f.severity as string) || "INFO";
      const tags = (f.tags as string[])?.length ? ` \`${(f.tags as string[]).join("`, `")}\`` : "";
      lines.push(`- [ ] **${sev}** ${loc} — ${f.message}${tags}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.accessToken) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  const { repos, categories } = await req.json() as {
    repos: { slug: string; issues: Record<string, Record<string, unknown>[]>; metrics: Record<string, number> }[];
    categories: string[];
  };

  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (data: Record<string, unknown>) => {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
      };

      const ghHeaders = {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${session.accessToken}`,
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
      };

      let totalCreated = 0;
      let totalUpdated = 0;
      let totalSkipped = 0;
      let totalFailed = 0;

      for (const repo of repos) {
        const [owner, repoName] = repo.slug.split("/");

        for (const cat of categories) {
          const issueKey = cat === "bugs" ? "bugs" : cat === "codeSmells" ? "codeSmells" : "vulnerabilities";
          const items = repo.issues?.[issueKey] ?? [];
          const metricCount = repo.metrics?.[issueKey] ?? 0;
          const count = items.length || metricCount;

          if (count === 0) {
            send({ type: "skip", repo: repo.slug, category: cat, reason: "no issues" });
            totalSkipped++;
            continue;
          }

          let title: string;
          let body: string;
          let labels: string[];

          if (cat === "bugs") {
            title = `[GitRoll] ${count} Bug${count !== 1 ? "s" : ""} Found`;
            labels = ["gitroll", "bug"];
            body = items.length > 0
              ? `## ${count} Bug${count !== 1 ? "s" : ""} Found\n\n| Metric | Value |\n|--------|-------|\n| Bugs | ${count} |\n| Reliability Rating | ${repo.metrics?.reliabilityRating}/5 |\n\n---\n\n${formatFindings(items)}\n\n---\n_Report generated by [GitRoll](https://gitroll.io) scan._`
              : `## ${count} Bug${count !== 1 ? "s" : ""} Found\n\nDetailed breakdown unavailable (older scan).\n\n---\n_Report generated by [GitRoll](https://gitroll.io) scan._`;
          } else if (cat === "codeSmells") {
            title = `[GitRoll] ${count} Code Smell${count !== 1 ? "s" : ""} Found`;
            labels = ["gitroll", "code-smell"];
            body = items.length > 0
              ? `## ${count} Code Smell${count !== 1 ? "s" : ""} Found\n\n| Metric | Value |\n|--------|-------|\n| Code Smells | ${count} |\n| Maintainability Rating | ${repo.metrics?.sqaleRating}/5 |\n\n---\n\n${formatFindings(items)}\n\n---\n_Report generated by [GitRoll](https://gitroll.io) scan._`
              : `## ${count} Code Smell${count !== 1 ? "s" : ""} Found\n\nDetailed breakdown unavailable (older scan).\n\n---\n_Report generated by [GitRoll](https://gitroll.io) scan._`;
          } else {
            title = `[GitRoll] ${count} Vulnerabilit${count !== 1 ? "ies" : "y"} Found`;
            labels = ["gitroll", "security"];
            body = items.length > 0
              ? `## ${count} Vulnerabilit${count !== 1 ? "ies" : "y"} Found\n\n| Metric | Value |\n|--------|-------|\n| Vulnerabilities | ${count} |\n| Security Rating | ${repo.metrics?.securityRating}/5 |\n\n---\n\n${formatFindings(items)}\n\n---\n_Report generated by [GitRoll](https://gitroll.io) scan._`
              : `## ${count} Vulnerabilit${count !== 1 ? "ies" : "y"} Found\n\nDetailed breakdown unavailable (older scan).\n\n---\n_Report generated by [GitRoll](https://gitroll.io) scan._`;
          }

          try {
            // Check for existing issue
            const q = encodeURIComponent(`repo:${owner}/${repoName} in:title "${title}" type:issue`);
            const searchRes = await fetch(`https://api.github.com/search/issues?q=${q}`, { headers: ghHeaders });
            const searchData = await searchRes.json();
            const existing = searchData.items?.find((i: Record<string, unknown>) => i.title === title);

            if (existing) {
              await fetch(`https://api.github.com/repos/${owner}/${repoName}/issues/${existing.number}`, {
                method: "PATCH",
                headers: ghHeaders,
                body: JSON.stringify({ body }),
              });
              send({ type: "updated", repo: repo.slug, category: cat, url: (existing as { html_url: string }).html_url });
              totalUpdated++;
            } else {
              const createRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/issues`, {
                method: "POST",
                headers: ghHeaders,
                body: JSON.stringify({ title, body, labels }),
              });
              const created = await createRes.json();
              send({ type: "created", repo: repo.slug, category: cat, url: created.html_url });
              totalCreated++;
            }
          } catch (e) {
            const msg = e instanceof Error ? e.message : "Unknown error";
            send({ type: "error", repo: repo.slug, category: cat, error: msg });
            totalFailed++;
          }

          // Rate limit courtesy
          await new Promise((r) => setTimeout(r, 1500));
        }
      }

      send({ type: "done", totalCreated, totalUpdated, totalSkipped, totalFailed });
      controller.close();
    },
  });

  return new Response(stream, {
    headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive" },
  });
}
